name: Generate Template

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Install Leiningen
        run: |
          wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          sudo mv lein /usr/local/bin/lein

      - name: Generate Luminus project
        run: |
          lein new luminus leiningen-erp +h2 +immutant

      - name: Compress project
        run: |
          zip -r leiningen-erp.zip leiningen-erp

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: template-${{ github.run_number }}
          name: ERP Template ${{ github.run_number }}
          files: leiningen-erp.zip